# Generated by Django 2.2.4 on 2019-08-16 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('commeninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.CommenInfo')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('poll_image', models.URLField()),
                ('background_color', models.CharField(max_length=8)),
                ('poll_type', models.IntegerField(choices=[(0, 'MCQ'), (1, 'TEXT')], default=0)),
            ],
            bases=('polls.commeninfo',),
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('commeninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.CommenInfo')),
            ],
            bases=('polls.commeninfo',),
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('commeninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.CommenInfo')),
                ('gender', models.CharField(blank=True, max_length=11, null=True)),
                ('dob', models.DateField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
            bases=('polls.commeninfo',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('commeninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.CommenInfo')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
            bases=('polls.commeninfo',),
        ),
    ]
