# Generated by Django 2.2.4 on 2019-08-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('commeninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.CommenInfo')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number to be validated', max_length=15, unique=True, verbose_name='phone_number')),
                ('otp', models.CharField(help_text='otp to be send to the Phone number', max_length=6, verbose_name='OTP')),
                ('count', models.IntegerField(default=0, help_text='Number of OTP send.', verbose_name='Attempted count')),
                ('is_verified', models.BooleanField(default=False, help_text='If it is true, this means user has validated otp correctly', verbose_name='is_verified')),
            ],
            bases=('polls.commeninfo',),
        ),
    ]
