# Generated by Django 2.2.4 on 2019-08-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190816_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='email',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
