# Generated by Django 2.2.4 on 2019-08-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190818_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='public',
        ),
        migrations.AddField(
            model_name='question',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
