# Generated by Django 2.2.4 on 2019-08-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_responders'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.TextField(default='Answer'),
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
