# Generated by Django 2.2.4 on 2019-08-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190818_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('commeninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.CommenInfo')),
                ('answer', models.TextField(default='Answer')),
            ],
            bases=('polls.commeninfo',),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
    ]
