# Generated by Django 2.2.4 on 2019-08-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190818_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswer',
            name='question_poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
