# Generated by Django 2.2.4 on 2019-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190818_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
