# Generated by Django 2.2.4 on 2019-08-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190829_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='background_color',
        ),
    ]
